sprint2
ClevertecFrontendLab/sprint2-TatianaRusak pull request #1
Opened 2023-02-08 20:25 UTC by TatianaRusak

2023-02-08 20:28 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675888130/slider%20one%20foto%20768px.png)

2023-02-08 21:01 UTC, klichkovskiy requested changes

2023-02-08 21:01 UTC, klichkovskiy commented on src/pages/main/main-page.tsx
> +export const MainPage = () => {
![image](https://user-images.githubusercontent.com/62481116/217649810-2464a135-ec18-47ae-b75f-a9721999f92f.png)
Поправь верстку везде!!!

2023-02-08 23:54 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 10.
Количество непройденных тестов: 2.
***
**Test width 1440px -- test navigation view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/Test%20width%201440px%20--%20test%20navigation%20view%20(failed).png)
***
**Test width 768px -- test navigation view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/Test%20width%20768px%20--%20test%20navigation%20view%20(failed).png)
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675900453/slider%20one%20foto%20768px.png)

2023-02-09 01:14 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675905273/slider%20one%20foto%20768px.png)

2023-02-09 08:32 UTC, klichkovskiy requested changes
Пересмотри еще раз внимательно!

2023-02-09 08:32 UTC, klichkovskiy commented on src/index.tsx
> +import React from 'react';
![image](https://user-images.githubusercontent.com/62481116/217758348-dc0dfd4b-69d3-4bc8-8ab1-74755f5c5b27.png)
Убери скролы

2023-02-09 08:32 UTC, klichkovskiy commented on src/index.tsx
> +import React from 'react';
![image](https://user-images.githubusercontent.com/62481116/217758550-2205bb33-b933-44c5-8077-10e5e72fa3b5.png)
А где меню?

2023-02-09 13:14 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675948476/slider%20one%20foto%20768px.png)

2023-02-09 14:30 UTC, klichkovskiy commented on src/components/menu/menu.tsx
> +  const isFirstVisit = useLocation().pathname === '/';
скрол страницы отключается если закрыть адаптивное меню не на крестик

2023-02-09 14:40 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675953601/slider%20one%20foto%20768px.png)

2023-02-09 14:43 UTC, klichkovskiy approved these changes
Удачи на 3 спринте!

2023-02-09 14:45 UTC, merged